/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PerroGlobo;

import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.GraphicsConfiguration;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.media.j3d.Transform3D;
import javax.vecmath.Vector3f;

/**
 *
 * @author DE LA CRUZ VILLANUEV
 */
public class PerroFrame extends javax.swing.JFrame {

    /**
     * Creates new form PerroFrame
     */
    
    crearEscenaGraficaPerro creaEscena;
    int contador = 0;
    public PerroFrame() {
        initComponents();
        GraphicsConfiguration config =SimpleUniverse.getPreferredConfiguration();
        Canvas3D lienzo=new Canvas3D(config);
        lienzo.setBounds(20, 20, 580, 500);
        this.setTitle("Perro globo graficación 2022");
        this.add(lienzo);
        this.setBounds(250, 50, 800, 600);
        setLocationRelativeTo(null);
        BranchGroup Scene=new BranchGroup();
        creaEscena= new crearEscenaGraficaPerro();
        Scene=creaEscena.objRaiz;
        SimpleUniverse n=new SimpleUniverse(lienzo);
        n.getViewingPlatform().setNominalViewingTransform();
        n.addBranchGraph(Scene);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnCaminar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCaminar.setText("Caminar");
        btnCaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(btnCaminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCaminar)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminarActionPerformed
        contador++;
        
        Transform3D leerPanza = new Transform3D();
        Transform3D MoverPanza = new Transform3D();
        creaEscena.panza.tgCapsula.getTransform(leerPanza);
        MoverPanza.setTranslation(new Vector3f(0.0f,-0.02f,0.0f));
        leerPanza.mul(MoverPanza);
        creaEscena.panza.tgCapsula.setTransform(leerPanza);
        
        
        if(contador<5){
            Transform3D leer = new Transform3D();
            Transform3D giro = new Transform3D();
            creaEscena.tgMoverEsferaPDD.getTransform(leer);
            giro.rotZ(Math.PI/180*15);
            leer.mul(giro);
            creaEscena.tgMoverEsferaPDD.setTransform(leer);

            Transform3D leer2 = new Transform3D();
            Transform3D giro2 = new Transform3D();
            creaEscena.tgMoverEsferaPDI.getTransform(leer2);
            giro2.rotZ(Math.PI/180*-15);
            leer2.mul(giro2);
            creaEscena.tgMoverEsferaPDI.setTransform(leer2);
        }
        else if(contador<9)
        {
            Transform3D leer = new Transform3D();
            Transform3D giro = new Transform3D();
            creaEscena.tgMoverEsferaPDD.getTransform(leer);
            giro.rotZ(Math.PI/180*-15);
            leer.mul(giro);
            creaEscena.tgMoverEsferaPDD.setTransform(leer);

            Transform3D leer2 = new Transform3D();
            Transform3D giro2 = new Transform3D();
            creaEscena.tgMoverEsferaPDI.getTransform(leer2);
            giro2.rotZ(Math.PI/180*15);
            leer2.mul(giro2);
            creaEscena.tgMoverEsferaPDI.setTransform(leer2);
        }
     
        
    }//GEN-LAST:event_btnCaminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaminar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
